default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_depodoc
  password: '120880'


development:
  <<: *default
  database: depodoc_development

test:
  <<: *default
  database: depodoc_test

production:
  <<: *default
  database: depodoc_production



users_default: &users_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_tm2
  password: '120880'


users_development: 
  <<: *users_default
  database: <%= ENV["USERS_DEVELOPMENT_DATABASE"] %>

users_test:
  <<: *users_default  
  database: tm2t_test

users_production:
  <<: *users_default  
  database: <%= ENV["USERS_PRODUCTION_DATABASE"] %>
