primary_default: &primary_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_depodoc
  password: '120880'
  migrations_paths: 'db/migrate'

tm2_default: &tm2_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_tm2
  password: '120880'
  migrations_paths: 'db/tm2_migrate'



development:
  primary:
    <<: *primary_default
    database: depodoc_development
  tm2_db:
    <<: *tm2_default
    # database: tm2t_development
    database: <%= ENV["USERS_DEVELOPMENT_DATABASE"] %>

production:
  primary:
    <<: *primary_default
    database: depodoc_production
  tm2_db:
    <<: *tm2_default
    # database: tm2t_production
    database: <%= ENV["USERS_PRODUCTION_DATABASE"] %>


test:
  primary:
    <<: *primary_default
    database: depodoc_test
  tm2_db:
    <<: *tm2_default
    database: tm2t_test


#  database: tm2t_production
#  host: 192.168.20.33
#  port: 3306

