export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS'
export const FETCH_DOCUMENTS_OK = 'FETCH_DOCUMENTS_OK'
export const FETCH_DOCUMENTS_START = 'FETCH_DOCUMENTS_START'
export const FETCH_DOCUMENTS_ERROR = 'FETCH_DOCUMENTS_ERROR'

export const RESET_DOCUMENTS = 'RESET_DOCUMENTS'