export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS'
export const FETCH_DOCUMENTS_OK = 'FETCH_DOCUMENTS_OK'
export const FETCH_DOCUMENTS_START = 'FETCH_DOCUMENTS_START'
export const FETCH_DOCUMENTS_ERROR = 'FETCH_DOCUMENTS_ERROR'

export const POST_DOCUMENT_START = 'POST_DOCUMENT_START'
export const POST_DOCUMENT_OK = 'POST_DOCUMENT_OK'
export const POST_DOCUMENT_ERROR = 'POST_DOCUMENT_ERROR'


export const RESET_DOCUMENTS = 'RESET_DOCUMENTS'

export const FETCH_VOC_OK = 'FETCH_VOC_OK'
export const FETCH_VOC_START = 'FETCH_VOC_START'
export const FETCH_VOC_ERROR = 'FETCH_VOC_ERROR'